In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data = pd.read_excel('Simmons.xls')
data.head()

   Customer  Spending  Card  Coupon
0         1     2.291     1       0
1         2     3.215     1       0
2         3     2.135     1       0
3         4     3.924     0       0
4         5     2.528     1       0

In [5]:
data.describe()   # It is used to get some statistical detail

         Customer    Spending        Card      Coupon
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    3.333790    0.500000    0.400000
std     29.011492    1.741298    0.502519    0.492366
min      1.000000    1.058000    0.000000    0.000000
25%     25.750000    2.059000    0.000000    0.000000
50%     50.500000    2.805500    0.500000    0.000000
75%     75.250000    4.468250    1.000000    1.000000
max    100.000000    7.076000    1.000000    1.000000

In [6]:
data['Coupon'].unique()   # It gives unique value in perticular column
data['Coupon'].value_counts()

Coupon
0    60
1    40
Name: count, dtype: int64

In [7]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [8]:
x = data[['Card', 'Spending']]
y = data['Coupon'].values.reshape(-1, 1)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

In [10]:
len(x_train), len(y_train), len(x_test), len(y_test)

(75, 75, 25, 25)

In [11]:
Lreg = LogisticRegression(solver='lbfgs')
Lreg.fit(x_train, y_train.ravel())   # Ravel() will return 1D array

LogisticRegression()

In [12]:
y_predict = Lreg.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0])

In [13]:
y_predict_train = Lreg.predict(x_train)
y_predict_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0])

In [14]:
y_prob_train = Lreg.predict_proba(x_train)[:, 1]
y_prob_train.reshape(1, -1)

array([[0.49618288, 0.32880558, 0.44331124, 0.33320598, 0.41459023,
        0.32890093, 0.39748721, 0.66918819, 0.25845659, 0.63670531,
        0.29274878, 0.28467622, 0.51588732, 0.41994733, 0.24343741,
        0.5285169 , 0.47961622, 0.52801323, 0.3319115 , 0.27458272,
        0.49175558, 0.6325985 , 0.24691508, 0.47090915, 0.27842841,
        0.41661746, 0.36154674, 0.49971207, 0.23623138, 0.37863254,
        0.48810439, 0.28878446, 0.28564488, 0.3723519 , 0.65307608,
        0.43809375, 0.33638085, 0.40409358, 0.23432709, 0.37285684,
        0.49971207, 0.39771263, 0.32880558, 0.25783611, 0.47390468,
        0.4288115 , 0.26521947, 0.33320598, 0.54682415, 0.45447877,
        0.44323889, 0.49652615, 0.60064794, 0.3899266 , 0.49150494,
        0.27415269, 0.27786462, 0.67461641, 0.28195703, 0.48594587,
        0.38631757, 0.31373574, 0.42812388, 0.27419567, 0.44373772,
        0.41632126, 0.64198463, 0.65707806, 0.44070086, 0.28195703,
        0.40215203, 0.43809375, 0.50973548, 0.57943883, 0.29042867]])

In [15]:
y_prob = Lreg.predict_proba(x_test)[:, 1]
y_prob.reshape(1, -1)

array([[0.52803246, 0.49517625, 0.45705046, 0.27712842, 0.34389496,
        0.26826124, 0.27712842, 0.60767304, 0.42838832, 0.43639299,
        0.31387527, 0.23677742, 0.45705046, 0.43600217, 0.37599363,
        0.44902215, 0.46949093, 0.68519265, 0.251685  , 0.47074771,
        0.42363481, 0.56580175, 0.5279248 , 0.40305375, 0.27458272]])

In [16]:
# Summary for logistic model
x = data[['Spending', 'Card']]
y = data['Coupon']

In [17]:
import statsmodels.api as sm

In [18]:
x1 = sm.add_constant(x)
logit_model = sm.Logit(y, x1)
result = logit_model.fit()

Optimization terminated successfully.
         Current function value: 0.604869
         Iterations 5

In [19]:
print(result.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                 Coupon   No. Observations:                  100
Model:                          Logit   Df Residuals:                       97
Method:                           MLE   Df Model:                            2
Date:                Tue, 31 Mar 2026   Pseudo R-squ.:                  0.1012
Time:                        23:20:07   Log-Likelihood:                -60.487
converged:                       True   LL-Null:                       -67.301
Covariance Type:            nonrobust   LLR p-value:                  0.001098
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.1464      0.577     -3.718      0.000      -3.278      -1.015
Spending       0.3416      0.129      2.655      0.008       0.089       0.594
Card           1.0987      0.445      2.471      0.013       0.227       1.970
==============================================================================

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
score = accuracy_score(y_test, y_predict)
score

0.76

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test, y_predict)

array([[15,  1],
       [ 5,  4]])

In [24]:
tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()

In [25]:
print("True Negatives: ", tn)
print("False Positives: ", fp)
print("False Negatives: ", fn)
print("True Positives: ", tp)

True Negatives:  15
False Positives:  1
False Negatives:  5
True Positives:  4

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.75      0.94      0.83        16
           1       0.80      0.44      0.57         9

    accuracy                           0.76        25
   macro avg       0.78      0.69      0.70        25
weighted avg       0.77      0.76      0.74        25