In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Question
Difference of means from independent samples where the standard deviations are known

- A battery manufacturer is interested in increasing the average lifespan of a rechargeable battery.

- Two production processes are tested: process 1 is the current manufacturing method, and process 2 incorporates a new electrode material that is expected to increase battery life.

- From historical data, it is known that the standard deviation of battery lifespan is 15 hours, and this inherent variability is assumed to remain unchanged with the new material.

- 12 batteries are produced using process 1, and another 12 batteries are produced using process 2; the 24 batteries are tested in random order.

- The two-sample average lifespans are $\bar{x}_1 = 210$ hours and $\bar{x}_2 = 222$ hours, respectively.

- What conclusions can the manufacturer draw about the effectiveness of the new electrode material using $\alpha = 0.05$?

In [2]:

# * Scenario: Difference of means from independent samples with known standard deviations.
# * Solution: Two-sample z-test

# Null hypothesis: H0: mu1 - mu2 = 0
# Alternative hypothesis: H1: mu2 > m1

In [3]:
alpha = 0.05
# sample size
n = 12
# sample means
x1_bar, x2_bar = 210, 222
# Known standard deviation: sigma = 0.5
sigma = 15
# Based on the null hypothesis, the difference in means is expected to be zero
delta = 0

# standard error of the difference in means
se = np.sqrt(sigma**2 / n + sigma**2 / n)
# test statistic
z = ((x2_bar - x1_bar) - delta) / se
# p-value for one-tailed test
p_value = 1 - stats.norm.cdf(z)
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (z): {z:.4f}")
print(f"P-value: {p_value:.4f}")
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

Test statistic (z): 1.9596
P-value: 0.0250
Decision at alpha=0.05: reject the null hypothesis.

# Question

**Difference of means from independent samples with unknown but equal standard deviations**

* Two machining techniques are being evaluated to determine how they affect the mean surface roughness of a manufactured metal component.

* Technique 1 is currently used in production. Technique 2 is a viable alternative.

* Technique 2 reduces operating costs and should be adopted, provided it does not change the mean surface roughness.

* A study is conducted in the production facility and the results are shown below.

* Is there any difference between the mean surface roughness values?

* Use $\alpha = 0.05$ and assume equal variances.

---

### **Observed Surface Roughness (micrometers)**

| Observation | Technique 1 | Technique 2 |
| ----------- | ----------- | ----------- |
| 1           | 4.52        | 4.63        |
| 2           | 4.61        | 4.70        |
| 3           | 4.49        | 4.58        |
| 4           | 4.74        | 4.82        |
| 5           | 4.55        | 4.66        |
| 6           | 4.68        | 4.77        |
| 7           | 4.59        | 4.71        |
| 8           | 4.63        | 4.69        |

Suppose you only had the following summary statistics, what would you do then?

Sample means: $\bar{x_1} = 4.601, \quad \bar{x_2} = 4.695$

Corrected standard deviations: $s_1 = 0.083, \quad s_2 = 0.076$

In [4]:

# * Scenario: Difference of means from independent samples with unknown standard deviations.
# * Solution: Paired independent Two-sample t-test

# Null hypothesis: H0: mu1 - mu2 = 0
# Alternative hypothesis: H1: mu1 != mu2

In [5]:
sample1 = np.array([4.52, 4.61, 4.49, 4.74, 4.55, 4.68, 4.59, 4.63])
sample2 = np.array([4.63, 4.70, 4.58, 4.82, 4.66, 4.77, 4.71, 4.69])
alpha = 0.05

In [6]:
# Library use:
# If you have the data:
t_statistic, p_value = stats.ttest_ind(sample1, sample2, equal_var=True, alternative="two-sided")

decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (t) from scipy: {t_statistic:.4f}")
print(f"P-value from scipy: {p_value:.4f}")
print(f"Decision at alpha={alpha} from scipy: {decision} the null hypothesis.")

Test statistic (t) from scipy: -2.3611
P-value from scipy: 0.0333
Decision at alpha=0.05 from scipy: reject the null hypothesis.

In [7]:
# Library use:
# If you're not given the data but have the summary statistics, you can still use scipy to compute the t-test:
x1_bar, x2_bar = sample1.mean(), sample2.mean()
s1, s2 = sample1.std(ddof=1), sample2.std(ddof=1)
n1, n2 = len(sample1), len(sample2)

t_statistic, p_value = stats.ttest_ind_from_stats(
    mean1=x1_bar, std1=s1, nobs1=n1,
    mean2=x2_bar, std2=s2, nobs2=n2,
    equal_var=True,
    alternative="two-sided",
)
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (t) from scipy: {t_statistic:.4f}")
print(f"P-value from scipy: {p_value:.4f}")
print(f"Decision at alpha={alpha} from scipy: {decision} the null hypothesis.")

Test statistic (t) from scipy: -2.3611
P-value from scipy: 0.0333
Decision at alpha=0.05 from scipy: reject the null hypothesis.

In [8]:
# Manual calculation of the two-sample t-test statistic and p-value

x1_bar, x2_bar = sample1.mean(), sample2.mean()
# Corrected standard deviations from the sample
s1, s2 = sample1.std(ddof=1), sample2.std(ddof=1)
n1, n2 = len(sample1), len(sample2)

# Pooled standard deviation and standard error for two-sample t-test
sp = np.sqrt(((n1 - 1) * s1**2 + (n2 - 1) * s2**2) / (n1 + n2 - 2))
se = sp * np.sqrt(1/n1 + 1/n2)

# test statistic
delta = 0 # based on the H0
t_statistic = ((x2_bar - x1_bar) - delta) / se
# degrees of freedom for two-sample t-test
df = n1 + n2 - 2
# p-value for two-tailed t-test
alpha = 0.05
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df))
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (t): {t_statistic:.4f}")
print(f"P-value: {p_value:.4f}")
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

Test statistic (t): 2.3611
P-value: 0.0333
Decision at alpha=0.05: reject the null hypothesis.

# Question
**Difference of means between dependent paired samples**

* An article in the *Journal of Environmental Engineering* compares two instruments for measuring airborne particulate concentration in industrial facilities.

* Data for two instruments, Device A and Device B, when used at ten specific monitoring sites on the same day, are shown in the table below.

* We wish to determine whether there is any difference (on average) between the readings from the two devices.

* Use $\alpha = 0.05$

---

**Table: Particulate Concentration Readings $(\mu g / m^3)$**

| Site | Device A | Device B | 
| ---- | -------- | -------- | 
| 1    | 42.3     | 40.8     | 
| 2    | 38.7     | 37.9     | 
| 3    | 45.1     | 43.5     | 
| 4    | 47.8     | 45.9     | 
| 5    | 39.4     | 38.2     | 
| 6    | 41.6     | 40.4     | 
| 7    | 44.2     | 42.7     | 
| 8    | 46.0     | 44.1     | 
| 9    | 43.5     | 42.0     | 
| 10   | 48.3     | 46.6     | 

---

Is there evidence of a difference in the mean particulate concentration readings between Device A and Device B?

In [9]:

# * Scenario: Difference of means between dependent paired samples
# * Solution: Relative t-test

# Null hypothesis: H0: mu1 - mu2 = 0
# Alternative hypothesis: H1: mu1 != mu2

In [10]:
data = {
    "site": range(1, 11),
    "device_a": [42.3, 38.7, 45.1, 47.8, 39.4, 41.6, 44.2, 46.0, 43.5, 48.3],
    "device_b": [40.8, 37.9, 43.5, 45.9, 38.2, 40.4, 42.7, 44.1, 42.0, 46.6],
}

In [11]:
df = pd.DataFrame(data)
df["delta"] = df["device_a"] - df["device_b"]
df

   site  device_a  device_b  delta
0     1      42.3      40.8    1.5
1     2      38.7      37.9    0.8
2     3      45.1      43.5    1.6
3     4      47.8      45.9    1.9
4     5      39.4      38.2    1.2
5     6      41.6      40.4    1.2
6     7      44.2      42.7    1.5
7     8      46.0      44.1    1.9
8     9      43.5      42.0    1.5
9    10      48.3      46.6    1.7

In [12]:
# Library use:
t_statistic, p_value = stats.ttest_rel(df["device_a"], df["device_b"], alternative="two-sided")
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (t): {t_statistic:.4f}")
print(f"P-value: {p_value:.4f}")
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

Test statistic (t): 13.7944
P-value: 0.0000
Decision at alpha=0.05: reject the null hypothesis.

In [13]:
# Manual calculation of the paired t-test statistic and p-value

alpha = 0.05
# sample size
n = len(df)
# mean of the differences
d_bar = df["delta"].mean()
# standard deviation of the differences
s_d = df["delta"].std(ddof=1)
# standard error of the mean difference
se_d = s_d / np.sqrt(n)
# test statistic
t_statistic = (d_bar - 0) / se_d
# degrees of freedom for paired t-test
dof = n - 1
# p-value for two-tailed t-test
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), dof))
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Test statistic (t): {t_statistic:.4f}")
print(f"P-value: {p_value:.4f}")
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

Test statistic (t): 13.7944
P-value: 0.0000
Decision at alpha=0.05: reject the null hypothesis.

# Question
**Comparing Sample Variance**

* A hospital is evaluating two different automated blood pressure monitors for use in its emergency department.

* Both devices are calibrated to produce the same average systolic blood pressure reading.

* However, hospital administrators are concerned about measurement consistency and would like to adopt the device with lower variability.

* A random sample of ( $n_1 = 18$ ) patients is measured using Device A, resulting in a sample standard deviation of
  ( $s_1 = 6.4$ mmHg).

* A separate random sample of ( $n_2 = 15$ ) patients is measured using Device B, resulting in a sample standard deviation of
  ( $s_2 = 8.1$ mmHg).

* With 92% confidence for the ratio of the population variances, decide if one of the devices is preferrable.

In [14]:
# Approach 1: Using P-value

confidence_level = 0.92
alpha = 1 - confidence_level

# Always set the sample with higher variance as sample 1 for the F-test.
# This allows us to use the upper tail test.
s1, s2 = 8.1, 6.4 
n1, n2 = 15, 18

F = (s1 ** 2 / s2 ** 2)
dof1 = n1 - 1
dof2 = n2 - 1

f_critical = stats.f.ppf(1 - alpha, dof1, dof2)
decision = "reject" if F > f_critical else "fail to reject"

print(f"F-statistic: {F:.4f}")
print(f"Critical value: {f_critical:.4f}")
print(f"Decision at alpha={alpha:.2f}: {decision} the null hypothesis.")

F-statistic: 1.6018
Critical value: 2.0534
Decision at alpha=0.08: fail to reject the null hypothesis.

In [15]:
# Approach 2: Using Confidence Intervals

alpha_lower = alpha / 2
alpha_higher = 1 - alpha_lower

f_critical_lower = stats.f.ppf(alpha_lower, dof1, dof2)
f_critical_higher = stats.f.ppf(alpha_higher, dof1, dof2)

# * Notice that the order of denominators is reversed!
ci_lower = F / f_critical_higher
ci_higher = F / f_critical_lower

# Fail to reject if 1 is within the confidence interval, otherwise reject
decision = "fail to reject" if ci_lower < 1 and 1 < ci_higher else "reject"

print(f"{confidence_level * 100}% confidence interval for the ratio of variances: [{ci_lower:.4f}, {ci_higher:.4f}]")
print(f"Decision: {decision} the null hypothesis.")

92.0% confidence interval for the ratio of variances: [0.6504, 4.1267]
Decision: fail to reject the null hypothesis.

# ANOVA

A sports scientist wants to compare the effectiveness of three different training programs on improving vertical jump height in collegiate athletes.

The three programs are:

* Program A: Plyometric-focused training
* Program B: Strength-focused training
* Program C: Mixed training

After 8 weeks of training, a random sample of athletes from each group is tested. The improvement in vertical jump height (in centimeters) is recorded below.

---

### **Vertical Jump Improvement (cm)**

| Athlete | Program A | Program B | Program C |
| ------- | --------- | --------- | --------- |
| 1       | 4.8       | 6.1       | 5.4       |
| 2       | 5.2       | 5.8       | 5.7       |
| 3       | 4.5       | 6.4       | 5.3       |
| 4       | 5.0       | 6.0       | 5.6       |
| 5       | 4.9       | 6.3       | 5.2       |

---

### Questions
1. Is there evidence of a difference in the mean improvement among the three training programs ($\alpha = 0.05$)?
2. Perform post-hoc Tukey testing if needed.

In [16]:
# Data
data = dict(
    A=[4.8, 5.2, 4.5, 5.0, 4.9],
    B=[6.1, 5.8, 6.4, 6.0, 6.3],
    C=[5.4, 5.7, 5.3, 5.6, 5.2],
)
df = pd.DataFrame(data)
df

     A    B    C
0  4.8  6.1  5.4
1  5.2  5.8  5.7
2  4.5  6.4  5.3
3  5.0  6.0  5.6
4  4.9  6.3  5.2

## Using a Library

In [17]:
alpha = 0.05
f_stat, p_value = stats.f_oneway(df.A, df.B, df.C)

print(f"F-statistic: {f_stat:.2f}")
print(f"p-value: {p_value:.2E}")

decision = "reject" if p_value < alpha else "fail to reject"
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

F-statistic: 34.63
p-value: 1.04E-05
Decision at alpha=0.05: reject the null hypothesis.

There is evidence to suggest that the mean improvement differs significantly across programs.

## Manual ANOVA

In [18]:
# Step 1: Reshape the Data
df = df.melt(var_name="Program", value_name="Improvement")
df

   Program  Improvement
0        A          4.8
1        A          5.2
2        A          4.5
3        A          5.0
4        A          4.9
5        B          6.1
6        B          5.8
7        B          6.4
8        B          6.0
9        B          6.3
10       C          5.4
11       C          5.7
12       C          5.3
13       C          5.6
14       C          5.2

In [19]:
# Step 2: Compute Group Means and Overall Mean
group_means = df.groupby("Program")["Improvement"].mean()
overall_mean = df["Improvement"].mean()

print("Group Means:\n", group_means)
print()
print(f"Overall Mean: {overall_mean:.2f}")

Group Means:
 Program
A    4.88
B    6.12
C    5.44
Name: Improvement, dtype: float64

Overall Mean: 5.48

In [20]:
# Step 3: Compute Sum of Squares

# Step 3.1: Between-Group Sum of Squares (SSB)
n = len(df[df["Program"] == "A"]) # each group size
SSB = 0
for mean in group_means:
    SSB += n * (mean - overall_mean) ** 2
print(f"SSB: {SSB:.2f}")

# Step 3.2: Within-Group Sum of Squares (SSW)
SSW = 0
for program, group in df.groupby("Program")["Improvement"]:
    group_mean = group.mean()
    SSW += sum((group - group_mean) ** 2)
print(f"SSW: {SSW:.2f}")

# Step 3.3: Total Sum of Squares (SST)
SST = SSB + SSW
print(f"SST: {SST:.2f}")

# Alternative calculation of SST using the overall mean
# SST = sum((df["Improvement"] - overall_mean)**2)
# print(f"SST: {SST:.2f}")

SSB: 3.86
SSW: 0.67
SST: 4.52

In [21]:
# Step 4: Compute Degrees of Freedom
k = len(group_means) # number of groups
N = len(df) # total number of observations
df_between = k - 1
df_within = N - k
df_total = N - 1

In [22]:
# Step 5: Compute Mean Squares
MSB = SSB / df_between
MSW = SSW / df_within
print(f"Mean Square Between (MSB): {MSB:.2f}")
print(f"Mean Square Within (MSW): {MSW:.2f}")

Mean Square Between (MSB): 1.93
Mean Square Within (MSW): 0.06

In [23]:
# Step 6: Compute F-statistic and p-value
F_statistic = MSB / MSW
p_value = 1 - stats.f.cdf(F_statistic, df_between, df_within)
decision = "reject" if p_value < alpha else "fail to reject"

print(f"Manual F-statistic: {F_statistic:.2f}")
print(f"Manual p-value: {p_value:.2E}")
print(f"Decision at alpha={alpha}: {decision} the null hypothesis.")

Manual F-statistic: 34.63
Manual p-value: 1.04E-05
Decision at alpha=0.05: reject the null hypothesis.

## Post-hoc Tukey's HSD test

In [24]:
tukey = pairwise_tukeyhsd(
    endog=df["Improvement"],
    groups=df["Program"],
    alpha=0.05
)

# note: meandiff is mean(group2) - mean(group1)
print(tukey)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B     1.24    0.0  0.8419  1.6381   True
     A      C     0.56 0.0072  0.1619  0.9581   True
     B      C    -0.68 0.0018 -1.0781 -0.2819   True
----------------------------------------------------

- Program B has the highest mean improvement, followed by Program C, and then Program A.
- The Tukey HSD test results indicate that the differences in mean improvements between all pairs of programs (A vs B, A vs C, and B vs C) are statistically significant at the 0.05 significance level.