In [1]:
import pandas as pd
import numpy as np
import scipy
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [2]:
df = pd.read_excel('RBD.xlsx')
df

   System A  System B  System C
0        15        15        18
1        14        14        14
2        10        11        15
3        13        12        17
4        16        13        16
5        13        13        13

In [3]:
data = pd.melt(
    df.reset_index(),
    id_vars=['index'],
    value_vars=['System A', 'System B', 'System C']
)

In [4]:
data.columns = ['index', 'treatments', 'value']
model = ols('value ~ C(treatments)', data=data).fit()
anova_table = sm.stats.anova_lm(model, typ=1)

In [5]:
anova_table

                 df  sum_sq    mean_sq         F    PR(>F)
C(treatments)   2.0    21.0  10.500000  3.214286  0.068903
Residual       15.0    49.0   3.266667       NaN       NaN

In [6]:
# Accept the null hypothesis

In [7]:
# SOlving RBD Example
data = pd.melt(
    df.reset_index(),
    id_vars=['index'],
    value_vars=['System A', 'System B', 'System C']
)

In [8]:
data.columns = ['block', 'treatments', 'value']
model = ols('value ~ C(block) + C(treatments)', data=data).fit()
anova_table = sm.stats.anova_lm(model, typ=1)

In [9]:
anova_table

                 df  sum_sq  mean_sq         F    PR(>F)
C(block)        5.0    30.0      6.0  3.157895  0.057399
C(treatments)   2.0    21.0     10.5  5.526316  0.024181
Residual       10.0    19.0      1.9       NaN       NaN

In [10]:
# Reject the null hypothesis

In [11]:
data.columns = ['blocks', 'treatments', 'value']

In [12]:
print(data)

    blocks treatments  value
0        0   System A     15
1        1   System A     14
2        2   System A     10
3        3   System A     13
4        4   System A     16
5        5   System A     13
6        0   System B     15
7        1   System B     14
8        2   System B     11
9        3   System B     12
10       4   System B     13
11       5   System B     13
12       0   System C     18
13       1   System C     14
14       2   System C     15
15       3   System C     17
16       4   System C     16
17       5   System C     13