In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [2]:
df = pd.read_excel('RBD2.xlsx')
df

   chem1  chem2  chem3  chem4
0    1.3    2.2    1.8    3.9
1    1.6    2.4    1.7    4.4
2    0.5    0.4    0.6    2.0
3    1.2    2.0    1.5    4.1
4    1.1    1.8    1.3    3.4

In [3]:
data = pd.melt(
    df.reset_index(),
    id_vars=['index'],
    value_vars=['chem1', 'chem2', 'chem3', 'chem4']
)

In [4]:
data.columns = ['index', 'treatments', 'value']

In [5]:
model = ols('value ~ C(treatments)', data=data).fit()
anova_table = sm.stats.anova_lm(model, typ=1)
anova_table

                 df  sum_sq   mean_sq          F    PR(>F)
C(treatments)   3.0  18.044  6.014667  12.589569  0.000176
Residual       16.0   7.644  0.477750        NaN       NaN

In [6]:
data = pd.melt(
    df.reset_index(),
    id_vars=['index'],
    value_vars=['chem1', 'chem2', 'chem3', 'chem4']
)

In [7]:
data.columns = ['Fabric', 'Chemical', 'value']
data

    Fabric Chemical  value
0        0    chem1    1.3
1        1    chem1    1.6
2        2    chem1    0.5
3        3    chem1    1.2
4        4    chem1    1.1
5        0    chem2    2.2
6        1    chem2    2.4
7        2    chem2    0.4
8        3    chem2    2.0
9        4    chem2    1.8
10       0    chem3    1.8
11       1    chem3    1.7
12       2    chem3    0.6
13       3    chem3    1.5
14       4    chem3    1.3
15       0    chem4    3.9
16       1    chem4    4.4
17       2    chem4    2.0
18       3    chem4    4.1
19       4    chem4    3.4

In [8]:
model = ols('value ~ C(Fabric) + C(Chemical)', data=data).fit()
anova_table = sm.stats.anova_lm(model, typ=1)
anova_table

               df  sum_sq   mean_sq          F        PR(>F)
C(Fabric)     4.0   6.693  1.673250  21.113565  2.318913e-05
C(Chemical)   3.0  18.044  6.014667  75.894848  4.518310e-08
Residual     12.0   0.951  0.079250        NaN           NaN