In [1]:
import scipy
from scipy.stats import chi2
from scipy.stats import poisson

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Checking the GOF for Poisson Distribution:-
data = pd.read_excel('P_distribution.xlsx')
data

    Arrivals  Frequency
0          0          0
1          1          1
2          2          4
3          3         10
4          4         14
5          5         20
6          6         12
7          7         12
8          8          9
9          9          8
10        10          6
11        11          3
12        12          1

In [4]:
Observed_Freq = data['Frequency']

In [5]:
Observed_Freq

0      0
1      1
2      4
3     10
4     14
5     20
6     12
7     12
8      9
9      8
10     6
11     3
12     1
Name: Frequency, dtype: int64

In [6]:
total_arrival = 600
total_time_period = 100
mu = total_arrival / total_time_period

In [7]:
mu

6.0

In [8]:
Expected_Freq = []
for i in range(len(Observed_Freq)):
    E_Freq = 100 * poisson.pmf(i, mu)
    Expected_Freq.append(E_Freq)

In [9]:
Expected_Freq

[np.float64(0.24787521766663584),
 np.float64(1.4872513059998145),
 np.float64(4.461753917999444),
 np.float64(8.923507835998894),
 np.float64(13.385261753998332),
 np.float64(16.062314104797995),
 np.float64(16.06231410479801),
 np.float64(13.767697804112569),
 np.float64(10.32577335308442),
 np.float64(6.883848902056284),
 np.float64(4.130309341233764),
 np.float64(2.2528960043093247),
 np.float64(1.1264480021546681)]

In [10]:
Expected_Freq_round_off = [round(elem, 2) for elem in Expected_Freq]
Expected_Freq_round_off

[np.float64(0.25),
 np.float64(1.49),
 np.float64(4.46),
 np.float64(8.92),
 np.float64(13.39),
 np.float64(16.06),
 np.float64(16.06),
 np.float64(13.77),
 np.float64(10.33),
 np.float64(6.88),
 np.float64(4.13),
 np.float64(2.25),
 np.float64(1.13)]

In [11]:
df = pd.DataFrame(
    list(zip(Observed_Freq, Expected_Freq_round_off)),
    columns=['Observed Frequency', 'Expected Frequency']
)
df

    Observed Frequency  Expected Frequency
0                    0                0.25
1                    1                1.49
2                    4                4.46
3                   10                8.92
4                   14               13.39
5                   20               16.06
6                   12               16.06
7                   12               13.77
8                    9               10.33
9                    8                6.88
10                   6                4.13
11                   3                2.25
12                   1                1.13

In [12]:
obs_freq = [5, 10, 14, 20, 12, 12, 9, 8, 10]
expected_freq = [6.20, 8.92, 13.39, 16.06, 16.06, 13.77, 10.33, 6.88, 8.39]

In [13]:
scipy.stats.chisquare(obs_freq, expected_freq)

Power_divergenceResult(statistic=np.float64(3.2738182931105193), pvalue=np.float64(0.916017731732134))

In [14]:
# Checking the GOF for Uniform Distribution:-
chi2.ppf(0.99, 11)

np.float64(24.724970311318277)

In [15]:
x = [1610, 1585, 1649, 1590, 1540, 1397, 1410, 1350, 1495, 1564, 1602, 1655]

In [16]:
np.mean(x)

np.float64(1537.25)

In [17]:
exp_f = [1537.25, 1537.25, 1537.25, 1537.25, 1537.25, 1537.25,
         1537.25, 1537.25, 1537.25, 1537.25, 1537.25, 1537.25]

In [18]:
from scipy.stats import chisquare
chisquare(x, exp_f)

Power_divergenceResult(statistic=np.float64(74.37583346885673), pvalue=np.float64(1.78545252783034e-11))

In [19]:
# Checking the GOF for normal Distribution
A = [33, 43, 44, 45, 52, 52, 56, 58, 63, 64, 64, 65, 66, 68,
     70, 72, 73, 73, 74, 75, 83, 84, 85, 86, 91, 92, 94, 98, 102, 105]

In [20]:
mean = np.mean(A)
mean

np.float64(71.0)

In [21]:
std = np.std(A)
std

np.float64(18.226354544998845)

In [22]:
x = 1/6   # For 6 equal probability intervals:-

In [23]:
for j in range(1, 6):
    Prob_intervals = [scipy.stats.norm.ppf(j * x, mean, std)]
    print(Prob_intervals)

[np.float64(53.36743154175236)]
[np.float64(63.14941153083116)]
[np.float64(71.0)]
[np.float64(78.85058846916884)]
[np.float64(88.63256845824763)]

In [24]:
Expected_Freq = [5, 5, 5, 5, 5, 5]   # Will divide the normal distribution into 6 intervals at frequency 5 in each:-

In [25]:
Obs_f = [6, 3, 6, 5, 4, 6]

In [26]:
scipy.stats.chisquare(Obs_f, Expected_Freq)

Power_divergenceResult(statistic=np.float64(1.5999999999999999), pvalue=np.float64(0.9012493445012737))

In [27]:
chi2.ppf(0.95, 3)

np.float64(7.814727903251179)