In [1]:
import scipy
from scipy.stats import chi2
from scipy.stats import poisson
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('P_distribution.xlsx')

In [3]:
data

    Arrivals  Frequency
0          0          0
1          1          1
2          2          4
3          3         10
4          4         14
5          5         20
6          6         12
7          7         12
8          8          9
9          9          8
10        10          6
11        11          3
12        12          1

In [4]:
Observed_Freq = data['Frequency']

In [5]:
total_arrival = 600
total_time_period = 100
mu = total_arrival / total_time_period

In [6]:
Expected_Freq = []
for i in range(len(Observed_Freq)):
    E_Freq = 100 * poisson.pmf(i, mu)
    Expected_Freq.append(E_Freq)

In [7]:
Expected_Freq

[np.float64(0.24787521766663584),
 np.float64(1.4872513059998145),
 np.float64(4.461753917999444),
 np.float64(8.923507835998894),
 np.float64(13.385261753998332),
 np.float64(16.062314104797995),
 np.float64(16.06231410479801),
 np.float64(13.767697804112569),
 np.float64(10.32577335308442),
 np.float64(6.883848902056284),
 np.float64(4.130309341233764),
 np.float64(2.2528960043093247),
 np.float64(1.1264480021546681)]

In [8]:
Expected_Freq_round_off = [round(elem, 2) for elem in Expected_Freq]
Expected_Freq_round_off

[np.float64(0.25),
 np.float64(1.49),
 np.float64(4.46),
 np.float64(8.92),
 np.float64(13.39),
 np.float64(16.06),
 np.float64(16.06),
 np.float64(13.77),
 np.float64(10.33),
 np.float64(6.88),
 np.float64(4.13),
 np.float64(2.25),
 np.float64(1.13)]

In [9]:
df = pd.DataFrame(
    list(zip(Observed_Freq, Expected_Freq_round_off)),
    columns=['Observed Frequency', 'Expected Frequency']
)
df

    Observed Frequency  Expected Frequency
0                    0                0.25
1                    1                1.49
2                    4                4.46
3                   10                8.92
4                   14               13.39
5                   20               16.06
6                   12               16.06
7                   12               13.77
8                    9               10.33
9                    8                6.88
10                   6                4.13
11                   3                2.25
12                   1                1.13

In [10]:
obs_freq = [5, 10, 14, 20, 12, 12, 9, 8, 10]
expected_freq = [6.20, 8.92, 13.39, 16.06, 16.06, 13.77, 10.33, 6.88, 8.39]

In [11]:
scipy.stats.chisquare(obs_freq, expected_freq)

Power_divergenceResult(statistic=np.float64(3.2738182931105193), pvalue=np.float64(0.916017731732134))

In [12]:
chi2.ppf(0.95, 7)

np.float64(14.067140449340169)